### ISSUE TITLE
Method Illuminate\View\ComponentAttributeBag::twMerge does not exist.

### ISSUE THREAD

**Issue by brandymedia** [gehrisandro/tailwind-merge-laravel#2]
I've installed via composer and published the vendor files but I'm getting an error when updating:

`$attributes->merge()` to...

`$attributes->twMerge()`

Error:

`Method Illuminate\View\ComponentAttributeBag::twMerge does not exist.`

**Comment by gehrisandro** [comment]
Hi @brandymedia 

The issue has been fixed in the latest release (v0.1.0).

Thanks a lot for raising the issue.

**Comment by brandymedia** [comment]
Awesome, I can confirm this is now working. Thanks for the speedy fix 👍
