### ISSUE TITLE
Change of excepting behavior for Blade AttributeBag (v0.2.0)

### ISSUE THREAD

**Issue by Nowocyn** [gehrisandro/tailwind-merge-laravel#5]
https://github.com/gehrisandro/tailwind-merge-laravel/blob/e59e6d9769a4000209e8a4d1d9fe16fdab6fc09d/src/TailwindMergeServiceProvider.php#L70

with the latest tag v0.2.0, there was a change in the `twMerge()` macro. 
Before the update, it behaved like `$attributes->merge(...)`. Now you return `$this->only('class')` 

I did some tests with the new behavior and had to use first `$attributes->except('class')` and after that, I can call `twMerge()`. 

Was that change intended to break the previous behavior? 

Previous version: 
Component 1 (some/table/th.blade.php):
```PHP 
<th {{ $attributes->twMerge('px-3 py-3.5 text-left text-sm font-semibold text-gray-900') }}  scope="col">
    {{ $slot }}
</th>

```
Component 2:
```PHP
<x-some.table.th {{ $attributes->twMerge('cursor-pointer')}}  wire:click='orderBy({{ Js::from($order) }})' someTag="a">
    {{ $slot }}
</x-some.table.th>
```
Expectation: 
```HTML
<th  class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 cursor-pointer" wire:click='orderBy("orderValue")' someTag="a">
 some content
</th>
```

Actual Behavior since v0.2.0: 
```HTML
<th  class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 cursor-pointer">
 some content
</th>
```

Now my component looks like this:
```PHP
<th {{ $attributes->except('class') }} {{ $attributes->twMerge('px-3 py-3.5 text-left text-sm font-semibold text-gray-900') }}  scope="col">
    {{ $slot }}
</th>
```

**Comment by gehrisandro** [comment]
@Nowocyn Thank you very much for raising the issue. This change was not intended 😅 

With v0.2.1 you get the behaviour back you were used to.
